import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-2 px-4 border-b border-basic-dark">
          ServerActionsSample
        </header>
        <main className="container mx-auto flex grow">
          {children}
          {modal}
        </main>
      </body>
    </html>
  );
}
